### ISSUE TITLE
stylelint-disable-line doesn't work for multiline declarations

### ISSUE THREAD

**Issue by fiskhandlarn** [rstacruz/stylelint-rscss#11]
```
    &:checked ~ .single-steward-header, // stylelint-disable-line rscss/class-format
    &:checked ~ .toggle {
      //
    }
```

still triggers an error for the first line: 
`Invalid element name: '.single-steward-header'   rscss/class-format`

ATM you have to do this instead:
```
    // stylelint-disable
    &:checked ~ .single-steward-header,
    // stylelint-enable
    &:checked ~ .toggle {
      //
    }
```

Not sure if this is a styleline issue though.

**Comment by rstacruz** [comment]
Unfortunately, there's very little we can do here as a plugin... this is indeed Stylelint's territory. Thanks for the report!
