### ISSUE TITLE
what was the name of that "no-descendant" rule?

### ISSUE THREAD

**Issue by mik01aj** [rstacruz/stylelint-rscss#2]
- [Example config](https://github.com/rstacruz/stylelint-rscss/blob/master/docs/rules.md#rules) has `rscss/no-descendant-selector`.
- The [documentation section below](https://github.com/rstacruz/stylelint-rscss/blob/master/docs/rules.md#rscssno-descendant-combinator) is named `rscss/no-descendant-combinator`
- The code of that rule is in [`lib/no_descendant_operator.js`](https://github.com/rstacruz/stylelint-rscss/blob/master/lib/no_descendant_operator.js)

Why not change it to just `rscss/no-descendant` if it's so confusing?

**Comment by rstacruz** [comment]
Haha I had to change it many times during development. Still don't know
what to really call it. "No descendant combinator" seems most the
technically correct but is quite a mouthful...

**Comment by rstacruz** [comment]
Updated the docs to the correct one (`rscss/no-descendant-combinator`).

**Comment by mik01aj** [comment]
filename is still the same ("operator"). That's minor, but when the project grows...

**Comment by rstacruz** [comment]
oops! thanks for that, changed it. no release though, it's not something that actually changes any functionality.
