### ISSUE TITLE
class-format enhancement: an option to add my own regexes

### ISSUE THREAD

**Issue by mik01aj** [rstacruz/stylelint-rscss#4]
I see that the rule is configurable, but I can't make it fit my needs. My needs are:
- `.PascalCase` for components (this works)
- `.camelCase` for elements (can't do this)
- `-camelCase` for variants (almost the default)

Imho it would be reasonable to just accept regexes in the config, like this:

```
"rscss/class-format": {
    component: "[A-Z][a-zA-Z0-9]+",
    element - "[a-z][a-zA-Z0-9]+",
    helper - "_[a-z][a-zA-Z0-9]+",
    variant - "_[a-z][a-zA-Z0-9]+",
}
```

And of course the "RSCSS standard" conventions should be the default.

For now I'll stick to the built-in [`selector-class-pattern`](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-class-pattern/README.md) rule.

**Comment by rstacruz** [comment]
This works:

Component: "pascal-case"

As well as:

Component: /myregexp/

**Comment by rstacruz** [comment]
And the config format is in stylelint's strange two-item array convention
like this:

"rscss/class-format": [true, { component: "pascal-case" }]

**Comment by mik01aj** [comment]
Makes sense. 👍 

Then the rule just needs better documentation :)

**Comment by rstacruz** [comment]
I added an example on how to do it:

https://github.com/rstacruz/stylelint-rscss/blob/master/docs/rules.md

Hope that helps!

**Comment by mik01aj** [comment]
Thanks! 👍

**Comment by mik01aj** [comment]
So I tried this in my config:

```
    "rscss/class-format": [true, {
        "component": /^[A-Z][A-Za-z0-9]+$/,
        "element": /^[a-z][A-Za-z0-9]+$/,
        "variant": /^-[a-z][A-Za-z0-9]+$/,
    }]
```

and got this:

```
YAMLException: missed comma between flow collection entries in "......./.stylelintrc" at line 109, column 28:
                "component": /^[A-Z][A-Za-z0-9]+$/,
```

And when I try with strings like this:

```
    "rscss/class-format": [true, {
        "component": "^[A-Z][A-Za-z0-9]+$",
        "element": "^[a-z][A-Za-z0-9]+$",
        "variant": "^-[a-z][A-Za-z0-9]+$",
    }]
```

I get this:

```
TypeError: expr(...).test is not a function
    at ....../node_modules/stylelint-rscss/lib/class_format.js:134:31
    at Array.filter (native)
    at validateComponent (....../node_modules/stylelint-rscss/lib/class_format.js:133:28)
    at ....../node_modules/stylelint-rscss/lib/class_format.js:81:7
    at ....../node_modules/stylelint-rscss/lib/helpers/walk_selectors.js:41:43
    at Array.forEach (native)
    at ....../node_modules/stylelint-rscss/lib/helpers/walk_selectors.js:41:23
    at Processor.func (....../node_modules/stylelint-rscss/lib/helpers/flatten_rule.js:15:14)
    at Processor.process (....../node_modules/stylelint-rscss/node_modules/postcss-selector-parser/dist/processor.js:34:14)
    at flattenRule (....../node_modules/stylelint-rscss/lib/helpers/flatten_rule.js:16:6)
```

So I guess this ticket should be reopened.

**Comment by rstacruz** [comment]
Aw damn, I guess you can't have regexp objects in stylelintrc.

**Comment by harapeko** [comment]
@mik01aj pls, reopen issue

**Comment by rstacruz** [comment]
Okay, this is done and coming out on v0.4.0. Thanks for all your reports!

You can now do this:


```js
    "rscss/class-format": [true, {
        "component": "^[A-Z][A-Za-z0-9]+$",
        "element": "^[a-z][A-Za-z0-9]+$",
        "variant": "^-[a-z][A-Za-z0-9]+$",
    }]
```

**Comment by harapeko** [comment]
@rstacruz thx ! It works!!

**Comment by harapeko** [comment]
@rstacruz 

i tried this:
```
    "rscss/class-format": [true, {
      component: "/^([a-z][a-z0-9]*)(-([a-z][a-z0-9]*))+$/"
    }]
```

and tride this:
```
  "rules": {
    "rscss/class-format": [true, {
      component: "/^([a-z][a-z0-9]*)(-([a-z][a-z0-9]*))((-([a-z][a-z0-9]*))*)+$/"
    }]
  }
```

and got:
```
resources/assets/sp/sass/_components.search-form.scss
 18:1  ✖  Invalid component name: '.search-form'   rscss/class-format
```

**Comment by rstacruz** [comment]
Remove the `/` from that Regexp string and you should be good.
